// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	GAME_INSTANCES: DurableObjectNamespace;
	DISCORD_API_BASE: string;
}
