#:schema node_modules/wrangler/config-schema.json
name = "adventureboard-instance-manager"
main = "src/index.ts"
compatibility_date = "2024-05-12"

[vars]
DISCORD_API_BASE = "https://discord.com/api/v10"

[[durable_objects.bindings]]
name = "GAME_INSTANCES"
class_name = "GameInstance"

[[migrations]]
tag = "v1"
new_classes = ["GameInstance"]

[[kv_namespaces]]
binding = "ADVENTUREBOARD_KV"
id = "b017e45fc5f644c19f0e8f554945e998"

[d1_database]
binding = "DB"
database_name = "adventureboard"
database_id = "c55f2e53-5a57-4ead-81ed-c54ad6a31ee5"
